export default {
  definite_articles: [
    `Ich gehe in/das/Haus/ .`,
    `Ich schenke/dem/Lehrer/ einen Apfel.`,
    `Du siehst/das/Auto/ auf der Straße.`,
    `/Die/Mutter/ arbeitet als Chefin bei Samsung.`,
    `/Das/Wasser/ ist kalt.`,
    `/Die/Straße/ ist lang.`,
    `/Der/Hund/ frisst gerne Karotten.`,
    `Ich verstehe/den/Satz/ nicht.`,
    `Du findest/das/Buch/ .`,
    `Er ist/der/Lehrer/ .`,
    `Ich habe/den/Hut/ .`,
    `Sie hat/den/Apfel/ .`,
    `Ihr werdet/die/Spieler/ sein.`,
    `Wir können/den/Fernseher/ nicht sehen.`,
    `Du sagst/dem/Vater/ Bescheid.`,
    `Sie sagt/der/Katze/ nichts.`,
    `Sie können/der/Professorin/ alles sagen.`,
    `Ich mache/die/Hausaufgaben/ heute Abend.`,
    `Der Arzt gibt/dem/Mann/ ein Medikament.`,
    `Die Kellnerin gibt/dem/Kind/ einen Teller.`,
    `Wir geben/der/Frau/ ein Fahrrad.`,
    `Ihr gebt dem Polizisten/das/Geld.`,
    `Sie kommt auf/die/Bühne/ .`,
    `Wir kommen in/die/Wohnung/ .`,
    `Ihr kommt /der/Lehrerin/ entgegen.`,
    `Sie kommen aus /dem/Haus/ heraus`,
    `Ich will/ein/Eis/ .`,
    `Das Kind will auf/den/Spielplatz/ gehen.`,
    `Du willst/ein/Fahrrad/ .`,
    `Was will er von/dem/Mann/ ?`,
    `Ihr geht morgens in/die/Schule/ .`,
    `Ich kann nicht in/den/Park/ gehen.`,
    `Sie soll über/die/Straße/ gehen.`,
    `Ich kann/den/Mond/ nicht mehr sehen.`,
    `Du lässt/den/Kaffee/ kalt werden.`,
    `Er steht neben/dem/Bus/ .`,
    `Sie steht abends in/dem/Wohnzimmer/ .`,
    `Sie finden/den/Schlüssel/ nicht.`,
    `Wir finden/die/Lampe/ in der Wohnung.`,
    `Ihr bleibt in/dem/Auto/ .`,
    `Die Wärme bleibt in/der/Wohnung/ .`,
    `Sie liegen an/dem/Strand/ .`,
    `Das Handtuch liegt auf/dem/Stuhl/ im Zimmer.`,
    `/Der/Bruder/ heißt Harald.`,
    `Du denkst über/die/Welt/ nach.`,
    `Wir denken über/die/Reise/ nach.`,
    `Ihr denkt an/die/Erinnerung/ zurück.`,
    `Ich denke an/den/Termin/ .`,
    `Bitte glaube/der/Hexe/ kein Wort.`,
    `Wir glauben an/die/Zukunft/ .`,
    `Du glaubst auch noch an/den/Weihnachtsmann/ .`,
    `Die Polizistin hält/den/Verkehr/ auf.`,
    `Heute halten wir/den/Regenschirm/ .`,
    `Unsere Familie hält/den/Arzt/ in Erinnerung.`,
    `Bitte nenne/das/Kind/ nicht schon wieder Harald.`,
    `Sie nennen/den/Ort/ im Laufe des Films.`,
    `Du magst/die/Birne/ lieber.`,
    `Ich mag/die/Blumen/ nicht.`,
    `Der Mann zeigt/dem/Fahrradfahrer/ den Weg.`,
    `Die Professorin zeigt auf/die/Tafel/ .`,
    `Sie zeigt der Mutter/das/Plakat/ .`,
    `Ihr zeigt/das/Problem/ auf.`,
    `Sie führen/die/Großmutter/ in das Zimmer.`,
    `Ich spreche gerne über/die/Arbeit/ und mein Leben.`,
    `Man kann/den/Gast/ morgens nicht ansprechen.`,
    `Wir sprechen nicht von/dem/Problem/ , sondern von der Lösung.`,
    `Du bringst/dem/Vater/ ein Glas kaltes, klares Wasser.`,
    `Wir leben in/dem/Haus/ auf der linken Seite.`,
    `Ich lebe lieber in/der/Stadt/ als auf dem Land.`,
    `Er fährt heute/das/Auto/ .`,
    `Sie fährt mit dem Fahrrad auf/das/Land/ .`,
    `Wir fahren mit/dem/Zug/ nach Busan.`,
    `Ihr fahrt oft in/die/Stadt/ .`,
    `Nein, ich meine nicht/das/Buch/, sondern die Tasche.`,
    `Du meinst also,/die/Schule/ gesehen zu haben.`,
    `Ich frage/die/Nachbarin/ nach einer Tasse Kaffee.`,
    `Du fragst den Lehrer nach/der/Pause/ , um was es im Unterricht ging.`,
    `Ihr fragt/die/Schwestern/ nach einer Antwort.`,
    `Der Mann kennt/den/Hund/ nicht.`,
    `Wir kennen/die/Stadt/ sehr gut.`,
    `Sie kennen/den/Film/ in- und auswendig.`,
    `Die Fahrkarte gilt bis zu/dem/Ende/ des Jahres.`,
    `Für alle gelten/die/Regeln/.`,
    `Ich stelle/die/Pflanze/ auf das Regal.`,
    `Du stellst das Regal in/das/Wohnzimmer/ .`,
    `Wir stellen/die/Uhr/ auf die neue Zeit um.`,
    `Sie spielt/das/Brettspiel/ .`,
    `Ihr spielt mit/den/Gefühlen/ anderer Menschen.`,
    `Er arbeitet in/dem/Büro/ von morgens bis spätabends.`,
    `Sie arbeiten bis in/die/Nacht/ .`,
    `Ich brauche/die/Hausaufgaben/ bis morgen früh.`,
    `Du brauchst/den/Tag/ gar nicht erst anfangen.`,
    `Wir brauchen/die/Tasche/ , um den Einkauf nach Hause zu tragen.`,
    `Ihr braucht sicher/die/Hilfe/ .`,
    `Ich folge/dem/Weg/ bis ich ankomme.`,
    `Sie folgt/dem/Geräusch/ .`,
    `Er lernt/die/Sprache/ gerne.`,
    `Ihr lernt mehr über/die/Geschichte/ als ich es konnte.`,
    `Von/dem/Lehrer/ können sie noch viel lernen.`,
    `Du bestehst/die/Prüfung/ im Handumdrehen.`,
    `Sie bestehen auf/die/Brote/ .`,
    `Man versteht/den/Satz/ nur schwer.`,
    `Er versteht/die/Sprache/ leider nicht.`,
    `Was kann man an/dem/Satz/ nicht verstehen?`,
    `Ich bekomme/das/Fahrrad/ .`,
    `Wir bekommen/den/Kuchen/ von unserer Großmutter.`,
    `Sie beginnen/das/Konzert/ .`,
    `Du erzählst mir bei/dem/Mittagessen/ von deiner Geschichte.`,
    `Ihr erzählt/die/Geschichte/ erneut.`,
    `Sie schreibt/den/Brief/ an ihren Vater.`,
    `Ich weiß nicht, wie ich/den/Buchstaben/ schreiben soll.`,
    `Ich laufe auf/dem/Teppich/ , der rot ist.`,
    `Er läuft/dem/Sänger/ hinterher.`,
    `Sie erkärt/dem/Großvater/ , was ein Smartphone ist.`,
    `Du kannst mir/die/Sprache/ gerne erklären.`,
    `Ihr sitzt auf/dem/Stuhl/ und an einem großen Tisch.`,
    `Wir fallen in/das/Loch/ .`,
    `Sie lesen/die/Bücher/ .`,
    `Wir reden mit/den/Eltern/ über das Kind.`,
    `Sie verbindet/das/Kabel/ mit dem Telefon.`,
  ],

  indefinite_articles: [
    `Ich gehe in/ein/Haus/ .`,
    `Ich schenke/einem/Lehrer/ einen Apfel.`,
    `Man versteht/einen/Satz/ beim Lesen.`,
    `Er versteht nur/eine/Sprache/ in Europa nicht.`,
    `Ihr sitzt auf/einem/Stuhl/ und an einem großen Tisch.`,
    `Wir fallen in/ein/Loch/ .`,
    `Sie lesen/ein/Buch/ .`,
    `Du brauchst/einen/Tag/ Urlaub.`,
    `Wir brauchen/eine/Tasche/ , um den Einkauf nach Hause zu tragen.`,
    `Ihr braucht sicher/eine/Karte/ .`,
    `Ich hätte gerne/ein/Brötchen/ .`,
    `Die Großmuter backt mir zum Geburtstag/einen/Kuchen/ .`,
    `Wenn du/eine/Sternschnuppe/ siehst, dann darfst du dir etwas wünschen.`,
    `Wir leben in/einer/Stadt/ , die Berlin heißt.`,
    `Heute kaufe ich/eine/Melone/ .`,
    `Ihr zieht in/eine/Wohnung/ um.`,
    'Die Kinder spielen/ein/Brettspiel/ im Wohnzimmer.',
    `Dem Verkäufer gebe ich/einen/Euro/ und fünfzig Cent.`,
    `Die Wanderer schlafen jeden Tag in/einem/Zelt/ .`,
    `Sie trägt/ein/Kleid/ und rote Gummistiefel.`,
    `Die Frau liest/eine/Zeitung/ .`,
    `Der Fahrer steigt aus/einem/Auto/ und grüßt uns.`,
    `/Einen/Apfel/ möchte ich gerne.`,
    '/Ein/Bauer/ erntet morgens die Kartoffeln.',
    `/Ein/Jahr/ hat dreihundertundfünfundsechzig Tage.`,
    `/Ein/Mensch/ erzählt mir seine Geschichte.`,
    `/Ein/Tag/ vergeht wie im Flug.`,
    `Ich vergesse die Zeit, wenn ich auf/einem/Konzert/ bin.`,
    `Deutschland ist/ein/Land/ mit einer langweiligen Flagge.`,
    `/Ein/Kind/ fährt auf dem Fahrrad.`,
    `Lass uns/ein/Land/ besuchen, dessen Sprache wir sprechen.`,
    `Du siehst/eine/Frau/ , die ein Auto fährt-`,
    `Der langweilige Film findet endlich/ein/Ende/ .`,
    `Sie braucht/eine/Woche/ , um das Projekt abzuschließen.`,
    `/Ein/Unternehmen/ will immer nur Profit machen.`,
    `Du machst noch schnell/ein/Foto/ von ihnen.`,
    `Die Schülerin hebt/eine/Hand/ und stellt eine Frage.`,
    `Du musst dem Mann in/ein/Auge schauen.`,
    `Habt ihr schon/eine/Zeit vereinbart, zu der ihr euch treffen wollt?`,
    `Ich kenne die genaue Größe/eines/Kopfes/ nicht.`,
    `Der Ausdruck/eines/Gesichts/ sagt oft mehr als tausend Worte.`,
    `Ich beschreibe die Farbe/einer/Tür/ .`,
    `Er hört/eine/Stimme/ , die er nicht kennt.`,
    `In/einer/Uhr/ befindet sich viel Metall.`,
    `Darf ich/ein/Wasser/ haben?`,
    `Geben Sie bitte dem Herrn/ein/Glas/ Wasser.`,
    `Sie möchten in/einer/Wohnung leben.`,
    `In/einem/Korb/ liegt ein Ei.`,
    `Darf ich/einen/Kaffee/ haben?`,
    `Geben Sie bitte der Dame/ein/Stück/ Torte.`,
    `Sie möchten in/einer/Welt leben, die besser als unsere ist.`,
  ],
};
